# Generated by Django 5.1.4 on 2025-04-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtracking',
            options={'verbose_name_plural': 'Email Tracking'},
        ),
    ]
