# Generated by Django 5.1.4 on 2025-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheapBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author_name', models.CharField(max_length=255)),
                ('pages', models.PositiveIntegerField()),
                ('is_epub', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('author_desc', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cheap Book',
                'verbose_name_plural': 'Cheap Books',
            },
        ),
    ]
