# Generated by Django 5.1.4 on 2025-05-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_ebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheapbook',
            name='author_desc',
        ),
    ]
