# Generated by Django 5.1.4 on 2025-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_ebook', '0002_remove_cheapbook_author_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheapbook',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
