# Generated by Django 5.1.4 on 2025-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0002_stockdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'verbose_name_plural': 'Stock Data'},
        ),
        migrations.AddField(
            model_name='stockdata',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
