# Generated by Django 5.1.4 on 2024-12-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uplodaded_at',
            new_name='uploaded_at',
        ),
    ]
