# Generated by Django 5.1.4 on 2024-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_rename_uplodaded_at_upload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/uploaded_data/'),
        ),
    ]
